# Generated by Django 6.0 on 2026-01-06 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClasseActif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Classe d'actif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe d'Actif",
                "verbose_name_plural": "Classes d'Actifs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Cotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type de cotation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotation",
                "verbose_name_plural": "Cotations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="FCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du FCP"
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de création"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "FCP",
                "verbose_name_plural": "FCPs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Pays"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="Code pays"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Secteur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="SecteurObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Secteur obligation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secteur Obligation",
                "verbose_name_plural": "Secteurs Obligations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Type de client"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de Client",
                "verbose_name_plural": "Types de Clients",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeFCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type de FCP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de FCP",
                "verbose_name_plural": "Types de FCP",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type d'opération"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'Opération",
                "verbose_name_plural": "Types d'Opérations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Benchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "benchmark_obligataire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Benchmark Obligataire",
                    ),
                ),
                (
                    "benchmark_actions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Benchmark Actions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark",
                "verbose_name_plural": "Benchmarks",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="fcp_app_ben_date_02588a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ActifNet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Montant de l'actif net",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actifs_nets",
                        to="fcp_app.fcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actif Net",
                "verbose_name_plural": "Actifs Nets",
                "ordering": ["-date", "fcp"],
                "indexes": [
                    models.Index(fields=["date"], name="fcp_app_act_date_7f5c17_idx"),
                    models.Index(
                        fields=["fcp", "date"], name="fcp_app_act_fcp_id_ca1301_idx"
                    ),
                ],
                "unique_together": {("fcp", "date")},
            },
        ),
        migrations.CreateModel(
            name="PoidsQuotidien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "actions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Poids Actions (%)",
                    ),
                ),
                (
                    "obligations",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Poids Obligations (%)",
                    ),
                ),
                (
                    "opcvm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Poids OPCVM (%)",
                    ),
                ),
                (
                    "liquidites",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Poids Liquidités (%)",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poids_quotidiens",
                        to="fcp_app.fcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poids Quotidien",
                "verbose_name_plural": "Poids Quotidiens",
                "ordering": ["-date", "fcp"],
                "indexes": [
                    models.Index(fields=["date"], name="fcp_app_poi_date_d5f60f_idx"),
                    models.Index(
                        fields=["fcp", "date"], name="fcp_app_poi_fcp_id_59657a_idx"
                    ),
                ],
                "unique_together": {("fcp", "date")},
            },
        ),
        migrations.CreateModel(
            name="CompositionFCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pourcentage",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.classeactif",
                        verbose_name="Classe d'actif",
                    ),
                ),
                (
                    "cotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.cotation",
                        verbose_name="Cotation",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="fcp_app.fcp",
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.pays",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.secteur",
                        verbose_name="Secteur",
                    ),
                ),
                (
                    "secteur_obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.secteurobligation",
                        verbose_name="Secteur obligation",
                    ),
                ),
                (
                    "type_fcp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fcp_app.typefcp",
                        verbose_name="Type de FCP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition FCP",
                "verbose_name_plural": "Compositions FCP",
                "ordering": ["fcp", "-pourcentage"],
                "indexes": [
                    models.Index(fields=["fcp"], name="fcp_app_com_fcp_id_67677f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SouscriptionRachat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="fcp_app.fcp",
                        verbose_name="FCP",
                    ),
                ),
                (
                    "type_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="fcp_app.typeclient",
                        verbose_name="Type de client",
                    ),
                ),
                (
                    "type_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="fcp_app.typeoperation",
                        verbose_name="Type d'opération",
                    ),
                ),
            ],
            options={
                "verbose_name": "Souscription/Rachat",
                "verbose_name_plural": "Souscriptions/Rachats",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="fcp_app_sou_date_679ada_idx"),
                    models.Index(
                        fields=["fcp", "date"], name="fcp_app_sou_fcp_id_f99ee5_idx"
                    ),
                    models.Index(
                        fields=["type_operation", "date"],
                        name="fcp_app_sou_type_op_efb843_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ValeurLiquidative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Valeur liquidative",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs_liquidatives",
                        to="fcp_app.fcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur Liquidative",
                "verbose_name_plural": "Valeurs Liquidatives",
                "ordering": ["-date", "fcp"],
                "indexes": [
                    models.Index(fields=["date"], name="fcp_app_val_date_4ac0ab_idx"),
                    models.Index(
                        fields=["fcp", "date"], name="fcp_app_val_fcp_id_a03b1c_idx"
                    ),
                ],
                "unique_together": {("fcp", "date")},
            },
        ),
    ]
