# Generated by Django 6.0.1 on 2026-01-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FicheSignaletique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du FCP"
                    ),
                ),
                (
                    "echelle_risque",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                        ],
                        verbose_name="Échelle de risque (1-7)",
                    ),
                ),
                (
                    "type_fond",
                    models.CharField(
                        choices=[
                            ("Diversifié", "Diversifié"),
                            ("Obligataire", "Obligataire"),
                            ("Actions", "Actions"),
                            ("Monétaire", "Monétaire"),
                        ],
                        max_length=20,
                        verbose_name="Type de fond",
                    ),
                ),
                (
                    "horizon",
                    models.IntegerField(
                        verbose_name="Horizon d'investissement (années)"
                    ),
                ),
                (
                    "benchmark_oblig",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Benchmark Obligataire (%)",
                    ),
                ),
                (
                    "benchmark_brvmc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Benchmark BRVM C (%)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "gestionnaire",
                    models.CharField(
                        default="CGF Bourse",
                        max_length=100,
                        verbose_name="Gestionnaire",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de création"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Fiche Signalétique",
                "verbose_name_plural": "Fiches Signalétiques",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="ValeurLiquidative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs_liquidatives",
                        to="fcp_app.fichesignaletique",
                        verbose_name="FCP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur Liquidative",
                "verbose_name_plural": "Valeurs Liquidatives",
                "ordering": ["-date", "fcp"],
                "unique_together": {("fcp", "date")},
            },
        ),
    ]
