# Generated by Django 6.0.1 on 2026-01-14 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VL_FCP_Actions_Pharmacie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_actions_pharmacie",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Actions Pharmacie",
                "verbose_name_plural": "VL FCP Actions Pharmacie",
                "db_table": "fcp_app_vl_actions_pharmacie",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Al_Baraka_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_al_baraka_2",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Al Baraka 2",
                "verbose_name_plural": "VL FCP Al Baraka 2",
                "db_table": "fcp_app_vl_al_baraka_2",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Assur_Senegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_assur_senegal",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Assur Senegal",
                "verbose_name_plural": "VL FCP Assur Senegal",
                "db_table": "fcp_app_vl_assur_senegal",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_BNDE_Valeurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=4,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_bnde_valeurs",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP BNDE Valeurs",
                "verbose_name_plural": "VL FCP BNDE Valeurs",
                "db_table": "fcp_app_vl_bnde_valeurs",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Capital_Retraite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=5,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_capital_retraite",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Capital Retraite",
                "verbose_name_plural": "VL FCP Capital Retraite",
                "db_table": "fcp_app_vl_capital_retraite",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Diaspora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=6,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_diaspora",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Diaspora",
                "verbose_name_plural": "VL FCP Diaspora",
                "db_table": "fcp_app_vl_diaspora",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Djolof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=7,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_djolof",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Djolof",
                "verbose_name_plural": "VL FCP Djolof",
                "db_table": "fcp_app_vl_djolof",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Expat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=8,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_expat",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Expat",
                "verbose_name_plural": "VL FCP Expat",
                "db_table": "fcp_app_vl_expat",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_IFC_BOAD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=9,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_ifc_boad",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP IFC-BOAD",
                "verbose_name_plural": "VL FCP IFC-BOAD",
                "db_table": "fcp_app_vl_ifc_boad",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Liquidite_Optimum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=10,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_liquidite_optimum",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Liquidité Optimum",
                "verbose_name_plural": "VL FCP Liquidité Optimum",
                "db_table": "fcp_app_vl_liquidite_optimum",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Placement_Avantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=11,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_placement_avantage",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Placement Avantage",
                "verbose_name_plural": "VL FCP Placement Avantage",
                "db_table": "fcp_app_vl_placement_avantage",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Placement_Croissance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=12,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_placement_croissance",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Placement Croissance",
                "verbose_name_plural": "VL FCP Placement Croissance",
                "db_table": "fcp_app_vl_placement_croissance",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Placement_Quietude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=13,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_placement_quietude",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Placement Quiétude",
                "verbose_name_plural": "VL FCP Placement Quiétude",
                "db_table": "fcp_app_vl_placement_quietude",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Postefinances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=14,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_postefinances",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Postefinances",
                "verbose_name_plural": "VL FCP Postefinances",
                "db_table": "fcp_app_vl_postefinances",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Rente_Perpetuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=15,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_rente_perpetuelle",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Rente Perpétuelle",
                "verbose_name_plural": "VL FCP Rente Perpétuelle",
                "db_table": "fcp_app_vl_rente_perpetuelle",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Salam_CI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=16,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_salam_ci",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Salam CI",
                "verbose_name_plural": "VL FCP Salam CI",
                "db_table": "fcp_app_vl_salam_ci",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Transvie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=17,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_transvie",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Transvie",
                "verbose_name_plural": "VL FCP Transvie",
                "db_table": "fcp_app_vl_transvie",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_UCA_Doguicimi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=18,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_uca_doguicimi",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP UCA Doguicimi",
                "verbose_name_plural": "VL FCP UCA Doguicimi",
                "db_table": "fcp_app_vl_uca_doguicimi",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Vision_Monetaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=19,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_vision_monetaire",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Vision Monétaire",
                "verbose_name_plural": "VL FCP Vision Monétaire",
                "db_table": "fcp_app_vl_vision_monetaire",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCP_Walo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_walo",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCP Walo",
                "verbose_name_plural": "VL FCP Walo",
                "db_table": "fcp_app_vl_walo",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCPCR_Sonatel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=21,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_sonatel",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCPCR Sonatel",
                "verbose_name_plural": "VL FCPCR Sonatel",
                "db_table": "fcp_app_vl_sonatel",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCPE_DP_World_Dakar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=22,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_dp_world_dakar",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCPE DP World Dakar",
                "verbose_name_plural": "VL FCPE DP World Dakar",
                "db_table": "fcp_app_vl_dp_world_dakar",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCPE_Force_PAD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=23,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_force_pad",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCPE Force PAD",
                "verbose_name_plural": "VL FCPE Force PAD",
                "db_table": "fcp_app_vl_force_pad",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCPE_Sini_Gnesigui",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=24,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_sini_gnesigui",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCPE Sini Gnesigui",
                "verbose_name_plural": "VL FCPE Sini Gnesigui",
                "db_table": "fcp_app_vl_sini_gnesigui",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VL_FCPR_SenFonds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Valeur Liquidative",
                    ),
                ),
                (
                    "actif_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Actif Net",
                    ),
                ),
                (
                    "nombre_parts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Nombre de parts",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        default=25,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vl_senfonds",
                        to="fcp_app.fichesignaletique",
                    ),
                ),
            ],
            options={
                "verbose_name": "VL FCPR Sen'Fonds",
                "verbose_name_plural": "VL FCPR Sen'Fonds",
                "db_table": "fcp_app_vl_senfonds",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ValeurLiquidative",
        ),
    ]
