# Generated by Django 6.0 on 2026-01-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheSignaletique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "echelle_risque",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Échelle de risque"
                    ),
                ),
                (
                    "type_fcp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Type de FCP",
                    ),
                ),
                (
                    "horizon_investissement",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Horizon d'investissement (années)",
                    ),
                ),
                (
                    "benchmark_obligataire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Benchmark Obligataire",
                    ),
                ),
                (
                    "benchmark_brvmc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Benchmark BRVMC (Actions)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "depositaire",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Dépositaire",
                    ),
                ),
                (
                    "frais_gestion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Frais de gestion (TTC de l'actif net / an)",
                    ),
                ),
                (
                    "frais_entree",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Frais d'entrée TTC",
                    ),
                ),
                (
                    "frais_sortie",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Frais de sortie TTC",
                    ),
                ),
                (
                    "fcp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiche_signaletique",
                        to="fcp_app.fcp",
                        verbose_name="FCP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche Signalétique",
                "verbose_name_plural": "Fiches Signalétiques",
                "ordering": ["fcp"],
            },
        ),
    ]
