# Generated by Django 5.2.10 on 2026-01-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcp_app", "0004_split_benchmark_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionPoche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_poche",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("OBLIGATION", "Obligation"),
                            ("LIQUIDITE", "Liquidité"),
                            ("FCP", "FCP"),
                        ],
                        max_length=20,
                        verbose_name="Type de poche",
                    ),
                ),
                (
                    "date_composition",
                    models.DateField(verbose_name="Date de composition"),
                ),
                (
                    "poids_poche",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage du total de l'actif",
                        max_digits=6,
                        verbose_name="Poids de la poche (%)",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Montant (XOF)",
                    ),
                ),
                (
                    "fcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poches",
                        to="fcp_app.fichesignaletique",
                        verbose_name="FCP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition - Poche",
                "verbose_name_plural": "Compositions - Poches",
                "ordering": ["fcp", "date_composition", "type_poche"],
                "unique_together": {("fcp", "type_poche", "date_composition")},
            },
        ),
        migrations.CreateModel(
            name="InstrumentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'instrument"
                    ),
                ),
                (
                    "code_isin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code ISIN"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "valorisation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valorisation (XOF)",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage dans la poche",
                        max_digits=6,
                        verbose_name="Poids (%)",
                    ),
                ),
                (
                    "secteur",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Ticker BRVM"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "poche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instruments",
                        to="fcp_app.compositionpoche",
                        verbose_name="Poche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument - Action",
                "verbose_name_plural": "Instruments - Actions",
                "db_table": "fcp_app_instrument_action",
                "ordering": ["-poids"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstrumentFCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'instrument"
                    ),
                ),
                (
                    "code_isin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code ISIN"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "valorisation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valorisation (XOF)",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage dans la poche",
                        max_digits=6,
                        verbose_name="Poids (%)",
                    ),
                ),
                (
                    "gestionnaire",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Gestionnaire du FCP",
                    ),
                ),
                (
                    "type_fcp",
                    models.CharField(
                        blank=True,
                        help_text="Diversifié, Obligataire, Actions, Monétaire",
                        max_length=50,
                        null=True,
                        verbose_name="Type de FCP",
                    ),
                ),
                (
                    "vl_souscription",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="VL de souscription",
                    ),
                ),
                (
                    "fcp_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investissements_recus",
                        to="fcp_app.fichesignaletique",
                        verbose_name="FCP cible (si géré par CGF)",
                    ),
                ),
                (
                    "poche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instruments",
                        to="fcp_app.compositionpoche",
                        verbose_name="Poche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument - FCP",
                "verbose_name_plural": "Instruments - FCP",
                "db_table": "fcp_app_instrument_fcp",
                "ordering": ["-poids"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstrumentLiquidite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'instrument"
                    ),
                ),
                (
                    "code_isin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code ISIN"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "valorisation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valorisation (XOF)",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage dans la poche",
                        max_digits=6,
                        verbose_name="Poids (%)",
                    ),
                ),
                (
                    "type_liquidite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAT", "Dépôt à Terme"),
                            ("COMPTE_COURANT", "Compte Courant"),
                            ("DAV", "Dépôt à Vue"),
                            ("PENSION", "Mise en Pension"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Type de liquidité",
                    ),
                ),
                (
                    "etablissement",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Établissement",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Taux de rémunération (%)",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "poche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instruments",
                        to="fcp_app.compositionpoche",
                        verbose_name="Poche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument - Liquidité",
                "verbose_name_plural": "Instruments - Liquidités",
                "db_table": "fcp_app_instrument_liquidite",
                "ordering": ["-poids"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstrumentObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'instrument"
                    ),
                ),
                (
                    "code_isin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code ISIN"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "valorisation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valorisation (XOF)",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage dans la poche",
                        max_digits=6,
                        verbose_name="Poids (%)",
                    ),
                ),
                (
                    "type_obligation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ETAT", "Obligation d'État"),
                            ("CORPORATE", "Obligation Corporate"),
                            ("TRESOR", "Bon du Trésor"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Type d'obligation",
                    ),
                ),
                (
                    "emetteur",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Émetteur"
                    ),
                ),
                (
                    "taux_nominal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Taux nominal (%)",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "maturite_residuelle",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maturité résiduelle (années)",
                    ),
                ),
                (
                    "poche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instruments",
                        to="fcp_app.compositionpoche",
                        verbose_name="Poche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument - Obligation",
                "verbose_name_plural": "Instruments - Obligations",
                "db_table": "fcp_app_instrument_obligation",
                "ordering": ["-poids"],
                "abstract": False,
            },
        ),
    ]
