# Generated by Django 5.2.10 on 2026-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcp_app", "0005_add_composition_poches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichesignaletique",
            name="type_fond",
            field=models.CharField(
                choices=[
                    ("Diversifié", "Diversifié"),
                    ("Obligataire", "Obligataire"),
                    ("Actions", "Actions"),
                    ("Monétaire", "Monétaire"),
                    ("Capital-Risque", "Capital-Risque"),
                ],
                max_length=20,
                verbose_name="Type de fond",
            ),
        ),
    ]
